agriculture:
  name: Agriculture
  unit_type: Gatherers
  description: Generates food for each worker.
  tooltip: +1 Food per worker
  population:
    max:  6
    current:  1
  generator:
    type: food
    per_worker: 1
resources:
  name: Woodlands
  unit_type: Stickpickers
  description: Generates resources for each worker.
  tooltip: +1 Resource per worker
  population:
    max: 4
    current: 1
  generator:
    type: resource
    per_worker: 1
military:
  name: Barracks
  unit_type: Recruit
  description: Drafts units to the military.
  tooltip: Military units will be moved to active defense during the following turn and this building will be emptied.
  population:
    max: 1
    current: 0
  generator:
    type: militia
    per_worker: 1
  effects:
    - worker_sacrifice