local_default: &local
  sessions:
    default:
      database: scratch_development
      hosts:
        - localhost:27017
      options:
        safe: true
        consistency: :strong
  options:
    #allow_dynamic_fields: true
    identity_map_enabled: true
    #include_root_in_json: false
    #include_type_for_serialization: false
    #preload_models: false
    #protect_sensitive_fields: true
    #raise_not_found_error: true
    #scope_overwrite_exception: true
    #skip_version_check: false
    use_activesupport_time_zone: true
    #use_utc: false

development:
  <<: *local
  
mac_dev:
  <<: *local
  
test:
  <<: *local
  sessions:
    default:
      database: scratch_test