settings:
  assets:
    manifest: public/assets
    precompile:
      - !ruby/regexp '/\w+\.(?!js|css).+/'
      - !ruby/regexp '/application.(css|js)$/'
  csrf:
    secret: twentynine is a prime number and that is useful in my calculations
  fonts:
    - "Merienda:400,700"
    - "Raleway:200,400,800"